-- MySQL Script generated by MySQL Workbench
-- Wed Jul  7 18:59:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alkemyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alkemyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alkemyDB` DEFAULT CHARACTER SET utf8 ;
USE `alkemyDB` ;

-- -----------------------------------------------------
-- Table `alkemyDB`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemyDB`.`character` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(500),
  `name` VARCHAR(45),
  `age` VARCHAR(45),
  `weight` VARCHAR(45),
  `history` VARCHAR(300),
  `movieORserie` VARCHAR(45),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alkemyDB`.`movieORserie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemyDB`.`movieORserie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(500),
  `title` VARCHAR(45),
  `date` VARCHAR(45),
  `rate` INT(11),
  `associedChar` VARCHAR(100),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alkemyDB`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemyDB`.`genre` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500),
  `image` VARCHAR(100),
  `movieORserie` VARCHAR(100),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
